version: "2.4"
services:
  mockServer:
      image: mockserver/mockserver:latest
      ports:
        -   1080:1080
      environment:
        # MOCKSERVER_DISABLE_LOGGING: "true"
        MOCKSERVER_LOG_LEVEL: INFO
        MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
        # MOCKSERVER_PERSIST_EXPECTATIONS: "true"
        MOCKSERVER_PERSISTED_EXPECTATIONS_PATH: /config/initializerJson.json
        MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
        MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json

      volumes:
        - type: bind
          source: .
          target: /config